### ISSUE TITLE
'System.NullReferenceException' occurs when starting up Visual Studio 2019 (Professional)

### ISSUE THREAD

**Issue by michaelm7456** [elishalom/netcodemetrics#10]
When starting up Visual Studio 2019 Professional, a Visual Studio MessageBox pops up advising the Extension has caused an issue and to check the following .xml file for more details.

C:\Users\UserName\AppData\Roaming\Microsoft\VisualStudio\16.0_43a43d77\ActivityLog.xml

[Contents of '**ActivityLog.xml**' file]

[**Stack Trace**]
<entry>
 <record>2529</record>
 <time>2019/05/07 14:20:45.911</time>
 <type>Error</type>
 <source>Editor or Editor Extension</source>
 <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A; at CodeMetrics.Adornments.MetricsAdornment.RepaintComplexity(ITextSnapshot textSnapshot)&#x000D;&#x000A; at CodeMetrics.Adornments.MetricsAdornment.OnLayoutChanged(Object sender, TextViewLayoutChangedEventArgs e)&#x000D;&#x000A; at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)</description>
 </entry>

**Comment by michaelm7456** [comment]
This looks to be very similar to [Issue # 3](https://github.com/elishalom/netcodemetrics/issues/3)

Where there is an issue related to the '**CodeMetrics.Adornments.MetricsAdornment.RepaintComplexity**' Method.

**Comment by elishalom** [comment]
A possible fix to this issue is in version 0.9.1.1

**Comment by coolhome** [comment]
Currently working for myself in VS2019

**Comment by michaelm7456** [comment]
I've since downloaded Version 0.9.1.1 and encountered no further occurrences '**System.NullReferenceException**' when starting Visual Studio 2019.

I'm happy for this one to be marked as resolved and will mark it as closed.

Many thanks for looking into this one guys!
