### ISSUE TITLE
References are missing: microsoft.visualstudio.component.coreeditor

### ISSUE THREAD

**Issue by LeoJHarris** [elishalom/netcodemetrics#8]
Hi cannot install extension into VS 2019 community preview, am getting: This extension cannot be installed because the following references are missing: microsoft.visualstudio.component.coreeditor

Not compatible with VS 2019?

**Comment by elishalom** [comment]
Unfortunately, the extension is not compatible with VS 2019.

**Comment by william-liebenberg** [comment]
any plans to add support for VS2019? it is such a useful extension. In fact its the I always install first :)

**Comment by michaelm7456** [comment]
It would be superb to have this compatible with Visual Studio 2019 if possible.

I've used this tool in Visual Studio 2017 and found it to be an excellent help for Refactoring work.

**Comment by michaelm7456** [comment]
I've added a Pull Request which contains changes that allow support for Visual Studio 2019.

This involved some minor updates to the Manifest file to allow later Versions and also updated the Version Range for the '**Microsoft.VisualStudio.Component.CoreEditor**' prerequisite.

[Pull Request #8](https://github.com/elishalom/netcodemetrics/pull/9)

It's currently working on my PC with Microsoft Visual Studio Community 2019 (Version 16.0.2)

Looking forward to using it with VS 2019.

Hope this helps!

**Comment by elishalom** [comment]
@michaelm7456, thank you! This is great!
I'll rebuild the project and publish it later this week.

**Comment by michaelm7456** [comment]
@elishalom no problem, many thanks for creating this great Extension!

Apologies for the disruption, I've added in one more commit to ensure support for Visual Studio 2012 - 2019.

The previous Pull Request I made would only have supported Versions 2015 - 2019 and introduced a regression for anyone using Visual Studio 2012 or 2013.

Thanks again!

**Comment by elishalom** [comment]
Thanks to @michaelm7456 help the extension supports now VS 2019. The new version is in [VS gallery](https://marketplace.visualstudio.com/items?itemName=Elisha.CodeMetrices).
